CLIENT_ID = "YOUR_CLIENT_ID"

CLIENT_SECRET = "YOUR_CLIENT_SECRET_ID"

API_KEY = "YOUR_API_KEY"

API_KEY_SECRET = "YOUR_API_SECRET_KEY"

BEARER_TOKEN = "YOUR_BEARER_TOKEN"


ACCESS_TOKEN = "YOUR_CONSUMER_TOKEN"
ACCESS_TOKEN_SECRET = "YOUR_CONSUMER_SECRET_TOKEN"

USER_ID = "THIS IS NOT REQUIRED, only for you if you want to store it somewhere"
